export const environment = {
  production: true,
  defaultLang: 'en',
  useThirdPartyAPI: false,
  thirdPartyAPIHost: 'https://enka.shinshin.moe/ui/',
  thirdPartyAPIPicType: '.png',
  footerMsgs: [
    'シロクマ',
    'Ծ‸Ծ',
    'ꉂꉂ꒰•̤▿•̤*ૢ꒱',
    'ि०॰०ॢी',
    'ʕ•ﻌ•ʔ',
    'o(´^｀)o',
    ',,Ծ‸Ծ,,',
    'つ♡⊂',
    '( ´•̥×•̥` )',
    'ฅ ˘ฅ',
    'ฅ՞•ﻌ•՞ฅ',
    '(՞•Ꙫ•՞)',
    '◔.̮◔✧',
    '_(√ ζ ε:)_',
    '⚆_⚆',
    '(ง ˙o˙)ว',
    '(๑◕ܫ￩๑)b',
    "ฅ'ω'ฅ♪",
    "◍'ㅅ'◍",
    '･◡･',
    '( •︠ˍ•︡ )',
    "|•'-'•) ✧",
    '*⸜( •ᴗ• )⸝*',
    '(｡•ᴗ-)_',
    '(,,•́.•̀,,)',
    '(⁎⁍̴̛ᴗ⁍̴̛⁎)',
    '´•ᴥ•`',
    '･ᴥ･',
    '•́‸ก',
    '(´ސު｀)',
    '( ˶ ❛ ꁞ ❛ ˶ )',
    '^•ﻌ•^',
    '⸜(˙▾˙)⸝⁺✧',
    '੭ ˙ᗜ˙ )੭',
    '(•ิ_•ิ)',
    '(..•˘_˘•..)',
    '_(:з」∠)_',
    'ヘ(￣ω￣ヘ)',
    '(′▽`〃)',
    '(′～`●)',
    '˙ε ˙',
    '˙0˙',
    '>ω<',
    '(　′o`)',
    '(●′ω`●)',
    '( ੭•͈ω•͈)੭',
    'ଘ(੭ˊ꒳​ˋ)੭✧',
    '(ง ˙˘˙ )ว',
    'ᕙ(⍢)ᕗ',
    'ʅ( ՞ਊ՞)ʃ',
    '⸜(๑’ᵕ’๑)⸝',
    '(ˊo̴̶̷̤ ᴗ o̴̶̷̤ˋ)',
  ],
  artifactEffectContentPreffix: '•',
  githubRepository: 'https://github.com/Kurarion/Genshin-Calc',
  apiProxyServer: 'https://genshin-calc.irisu.cc/',
  elementColorAlpha: '75',
  outputLog: false,
};
